version: 0.0.1
content:
  PlayedPodcastTTL: "1m" # defaults to a month
  CheckInterval: "1m" # defaults to 1 minute
  StrictPodcastSchedule: true
  Programs:
    - Name: "gettysburg10"
      Type: "file"
      Source: "./static/gettysburg10.wav"
      Timeslot:
        Begin: "11:00PM"
        End: "11:30PM"

