name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Apt update
        run: sudo apt update --fix-missing

      - name: Install dependencies
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: export CI=true && go test -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Apt update
        run: sudo apt update --fix-missing

      - name: Install dependencies
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      - name: Run Tests
        run: go test -json > TestResults.json

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results
          path: TestResults.json

  # configuration: https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.55.2